### ISSUE TITLE
Норм

### ISSUE THREAD

**Issue by karas4ik** [lazerphp/calculator-server#1]
В принципе норм работа если конечно сам делал тк много комментов в ненужных местах.

Но следует поработать на ридми так как у тебя там куча не нужной информации:

1.Слишком много описания работы кода (Пользователя нужно информации только как использовать) 

2. Ненужная никому структура проекта в ридми 

И тд 
P.s Если что я смотрю со стороны обычного пользователя которому не нужна информация о структуре проекта и куча текста о том как оно работает

**Comment by karas4ik** [comment]
Я баллы за это не снимал, но просто у тебя это оформлено не очень. Как вариант сделать более прикольные(оформление) или просто убрать

**Comment by karas4ik** [comment]
Я тут в посмотрел и только щас понял что может ридми гптшный и тут не написано как установить

**Comment by lazerphp** [comment]
Спасибо за проверку. Сделаю ридми симпатичнее:)
